### ISSUE TITLE
Installation instructions for pyopenms didn't work for me

### ISSUE THREAD

**Issue by tentrillion** [biosustain/pyOpenMS_UmetaFlow#5]
It was just a small change in the URL name for download, I think.

On an Apple M1 machine running Sonoma, I was going through the installation / usage instructions and got to this part:

```
(pyopenms) curt @ cf-homepro ➜  /Users/curt/umeta git:(main) pip install --index-url https://pypi.cs.uni-tuebingen.de/simple/ pyopenms-nightly
Looking in indexes: https://pypi.cs.uni-tuebingen.de/simple/
ERROR: Could not find a version that satisfies the requirement pyopenms-nightly (from versions: none)
ERROR: No matching distribution found for pyopenms-nightly
```

I was able to move forward by changing it to this version:

```
(pyopenms) curt @ cf-homepro ➜  /Users/curt/umeta git:(main) pip install --index-url https://pypi.cs.uni-tuebingen.de/simple/ pyopenms       
.de/simple/ pyopenms      
```

I'm not sure if this is specific to my platform (probably not? but maybe?), but figured I'd note the change here.

**Comment by axelwalter** [comment]
Sorry for the late reply. We have made updates to the notebooks including installation instructions.
You can install everything via a conda environment file now, or simply install pyopenms via pip (no need for nightly builds any more).
