### ISSUE TITLE
SiriusAdapterAlgorithm() function is missing from pyopenms 3.1 but not 3.0

### ISSUE THREAD

**Issue by tentrillion** [biosustain/pyOpenMS_UmetaFlow#6]
This means the `5_SIRIUS_CSI.ipynb` notebook in this repo will not work.

Solution/workaround:

when installing pyopenms as described in the README use this command:

`pip install --index-url https://pypi.cs.uni-tuebingen.de/simple/ pyopenms==3.0`

**Comment by eeko-kon** [comment]
Thank you! We are updating the repo to support siriusAdapter again.
