### ISSUE TITLE
Examples of raw data and stage results files

### ISSUE THREAD

**Issue by njliangdong** [biosustain/pyOpenMS_UmetaFlow#7]
Hi, Dear author of UmetaFlow,
    I am a fresh researcher of untargeted metabolomics, would you mind add certain examples files in repository? such raw data, stage results files, so that i could find if some steps of this workflow work or not. Thanks a lot!

**Comment by eeko-kon** [comment]
I m sorry , since moving to a diff organisation, I stopped receiving notifications for this! For example files please use the data under those dir https://github.com/biosustain/snakemake_UmetaFlow/tree/main/data
